stages:
  - test
  - build
  - release

# ... (vorherige Jobs wie test/build)

create_release:
  image: registry.gitlab.com/gitlab-org/cli:latest
  tags: [docker]
  stage: release
  before_script:
    - apk add --no-cache make zip git
  script:
    - make release

    # Version bestimmen
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        VERSION=$CI_COMMIT_TAG
      else
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.0.0")
        COMMIT_SHORT=$(git rev-parse --short=8 HEAD)
        VERSION="${LAST_TAG}-${COMMIT_SHORT}"
      fi
      echo "VERSION=$VERSION" >> release.env
      echo "🚀 Creating release: $VERSION"

    # Dynamische Asset-Links generieren
    - |
      echo "ASSETS<<" >> release.env
      for file in bin/releases/*; do
        filename=$(basename "$file")
        echo "- name: '📦 $filename'" >> release.env
        echo "  url: '$CI_PROJECT_URL/-/jobs/$CI_JOB_ID/artifacts/raw/bin/releases/$filename'" >> release.env
      done
      echo ">>ASSETS" >> release.env

    # Release-Beschreibung
    - |
      echo "RELEASE_DESCRIPTION<<EOF" >> release.env
      echo "🚀 Release $VERSION" >> release.env
      echo "" >> release.env
      echo "**Commit:** [\`${COMMIT_SHORT}\`]($CI_PROJECT_URL/-/commit/$CI_COMMIT_SHA)" >> release.env
      echo "**Pipeline:** [#$CI_PIPELINE_ID]($CI_PIPELINE_URL)" >> release.env
      echo "" >> release.env
      echo "## 📋 Changes since last release" >> release.env
      git log --oneline --pretty=format:"* %s" ${LAST_TAG}..HEAD >> release.env
      echo "" >> release.env
      echo "## 📦 Installation" >> release.env
      echo "\`\`\`bash" >> release.env
      echo "# Download and extract:" >> release.env
      echo "curl -L \$CI_PROJECT_URL/-/jobs/\$CI_JOB_ID/artifacts/raw/bin/releases/markscribe-<OS>-<ARCH>.tar.gz | tar -xz" >> release.env
      echo "\`\`\`" >> release.env
      echo "EOF" >> release.env

  artifacts:
    paths:
      - bin/releases/*.tar.gz
      - bin/releases/*.zip
    expire_in: 4 weeks
    reports:
      dotenv: release.env

  release:
    tag_name: $VERSION
    name: 'Release $VERSION'
    description: $RELEASE_DESCRIPTION
    assets:
      links: $ASSETS

  rules:
    - if: $CI_COMMIT_TAG                  # Automatisch für Tags
    - if: $CI_COMMIT_BRANCH == "master"     # Manuell für main (Pre-Releases)
      when: manual
      variables:
        VERSION: "nightly-$CI_COMMIT_SHORT_SHA"
